<<<<<<< HEAD
name: GitHub Pages
=======
name: CI
>>>>>>> parent of 1c0d857 (deploy: kputtur/kputtur.github.io@15001d7dde3c1057d41d9cc7e216c5886e5a4732)

on:
  push:
    branches:
      - main  # Set a branch to deploy
  workflow_dispatch: # Put here
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v3
=======
      - name: Git Checkout
        uses: actions/checkout@v3
>>>>>>> parent of 1c0d857 (deploy: kputtur/kputtur.github.io@15001d7dde3c1057d41d9cc7e216c5886e5a4732)
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          
      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
<<<<<<< HEAD
        if: ${{ github.ref == 'refs/heads/main' }}
=======
>>>>>>> parent of 1c0d857 (deploy: kputtur/kputtur.github.io@15001d7dde3c1057d41d9cc7e216c5886e5a4732)
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: kputtur/kputtur.github.io
          publish_dir: ./public
          #
          user_name: kputtur
          user_email: kiran.puttur@gmail.com
          publish_branch: master
